version: '3.8'
services:
  go-app:
    container_name: auth-go-sp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    container_name: mongodb-sp
    image: mongo:6.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER_MONGO}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD_MONGO}
      MONGO_INITDB_DATABASE: ${DB_MONGO_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

volumes:
  mongodb-data:

networks:
  app-network:
    driver: bridge