name: frontend
on:
  push:
    branches: [ main ]
    paths:
      - frontend/**
  pull_request:
    branches: [ main ]
    paths:
      - frontend/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/main
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Npm install
        run: npm ci
      - name: Run linters
        run: npm run lint
      - name: Run test
        run: npm run test
